import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getPublishedPosts, getPostBySlug, getPostBlocks } from '@/lib/notion';
import { renderBlocks } from '@/lib/notion-renderer';
import PasswordGate from '@/components/PasswordGate';

export const revalidate = 60;

export async function generateStaticParams() {
  const posts = await getPublishedPosts();
  return posts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = await getPostBySlug(slug);
  if (!post) return { title: 'Not Found' };
  return { title: post.title };
}

function formatDate(dateStr: string): string {
  if (!dateStr) return '';
  const d = new Date(dateStr + 'T00:00:00');
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export default async function BlogPost({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = await getPostBySlug(slug);
  if (!post) notFound();

  return (
    <article className="prose">
      <header className="mb-8">
        <p style={{ marginBottom: '0.5rem' }}>
          <Link
            href="/"
            className="text-sm no-underline hover:underline"
            style={{ color: 'var(--color-text-muted)' }}
          >
            &larr; Home
          </Link>
        </p>
        <h1 style={{ marginBottom: '0.25rem' }}>{post.title}</h1>
        <time
          dateTime={post.date}
          className="text-sm"
          style={{ color: 'var(--color-text-muted)' }}
        >
          {formatDate(post.date)}
        </time>
      </header>

      {post.isPrivate ? (
        <PasswordGate slug={post.slug} />
      ) : (
        <PostContent pageId={post.id} />
      )}
    </article>
  );
}

// Content is server-rendered from Notion API. The HTML is generated by our own
// notion-renderer.ts which escapes all text content, so this is safe.
async function PostContent({ pageId }: { pageId: string }) {
  const blocks = await getPostBlocks(pageId);
  const html = await renderBlocks(blocks);
  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
