import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getPublishedPosts, getPostBySlug, getPostBlocks } from '@/lib/notion';
import { renderBlocks, extractHeadings, countWords } from '@/lib/notion-renderer';
import PasswordGate from '@/components/PasswordGate';
import TableOfContents from '@/components/TableOfContents';

export const revalidate = 60;

export async function generateStaticParams() {
  const posts = await getPublishedPosts();
  return posts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = await getPostBySlug(slug);
  if (!post) return { title: 'Not Found' };
  return {
    title: post.title,
    description: post.description || undefined,
    openGraph: {
      title: post.title,
      description: post.description || undefined,
    },
  };
}

function formatDate(dateStr: string): string {
  if (!dateStr) return '';
  const d = new Date(dateStr + 'T00:00:00');
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

const WORDS_PER_MINUTE = 238;
const MIN_HEADINGS_FOR_TOC = 3;

export default async function BlogPost({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = await getPostBySlug(slug);
  if (!post) notFound();

  // Fetch blocks once so we can derive read time, headings, and rendered HTML
  const blocks = post.isPrivate ? [] : await getPostBlocks(post.id);
  const readTime = blocks.length ? Math.max(1, Math.ceil(countWords(blocks) / WORDS_PER_MINUTE)) : null;
  const headings = blocks.length ? extractHeadings(blocks) : [];
  const showToc = headings.length >= MIN_HEADINGS_FOR_TOC;

  return (
    <article className="prose">
      <header className="mb-8">
        <p style={{ marginBottom: '0.5rem' }}>
          <Link
            href="/"
            className="text-sm no-underline hover:underline"
            style={{ color: 'var(--color-text-muted)' }}
          >
            &larr; Home
          </Link>
        </p>
        <h1 style={{ marginBottom: '0.25rem' }}>{post.title}</h1>
        <div className="flex flex-wrap items-center gap-x-3 text-sm" style={{ color: 'var(--color-text-muted)' }}>
          <time dateTime={post.date}>{formatDate(post.date)}</time>
          {post.author && (
            <>
              <span aria-hidden="true">&middot;</span>
              <span>{post.author}</span>
            </>
          )}
          {readTime && (
            <>
              <span aria-hidden="true">&middot;</span>
              <span>{readTime} min read</span>
            </>
          )}
        </div>
        {post.tags.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-3">
            {post.tags.map((tag) => (
              <span
                key={tag}
                className="text-xs px-2 py-0.5 rounded-full"
                style={{
                  backgroundColor: 'var(--color-code-bg)',
                  color: 'var(--color-text-muted)',
                }}
              >
                {tag}
              </span>
            ))}
          </div>
        )}
      </header>

      {post.isPrivate ? (
        <PasswordGate slug={post.slug} />
      ) : (
        <PostContent blocks={blocks} showToc={showToc} headings={headings} />
      )}
    </article>
  );
}

// Content is server-rendered from Notion API. The HTML is generated by our own
// notion-renderer.ts which escapes all text content, so this is safe.
async function PostContent({
  blocks,
  showToc,
  headings,
}: {
  blocks: Awaited<ReturnType<typeof getPostBlocks>>;
  showToc: boolean;
  headings: ReturnType<typeof extractHeadings>;
}) {
  const html = await renderBlocks(blocks);
  return (
    <>
      {showToc && <TableOfContents headings={headings} />}
      <div dangerouslySetInnerHTML={{ __html: html }} />
    </>
  );
}
